export const UI_LABELS = {
  retry: "Retry",
  continue: "Continue",
  saveChanges: "Save changes",
  create: "Create",
  createOrg: "Create org",
  createProject: "Create project",
  createProgram: "Create program",
  createInvoice: "Create invoice",
  createInvite: "Create invite",
  publish: "Publish",
  refresh: "Refresh",
  review: "Review",
  approve: "Approve",
  reject: "Reject",
  requestRevision: "Request revision",
  submit: "Submit",
  registerValidator: "Register validator",
  markSent: "Mark sent",
  markPaid: "Mark paid",
  add: "Add",
  edit: "Edit",
  delete: "Delete",
  stop: "Stop",
  start: "Start",
  addManualEntry: "Add manual entry",
  generateInvoice: "Generate invoice",
  buy: "Buy",
  backToOrgs: "Back to orgs",
  manageOrg: "Manage org",
  viewOrg: "View org",
  signIn: "Sign in",
  verify: "Verify",
};

export const ERROR_COPY = {
  auth: "Sign in to continue.",
  validation: "Please check the details and try again.",
  not_found: "We couldn't find what you requested.",
  rate_limited: "You're doing that too often. Please try again shortly.",
  server: "The service is temporarily unavailable. Please try again.",
  network: "We couldn't reach the service. Check your connection and retry.",
  chain: {
    default: "We couldn't confirm the on-chain result yet.",
    rejected: "Transaction cancelled.",
    reverted: "Transaction reverted.",
    wrongChain: "Switch to the required network.",
    unknown: "Unable to confirm right now.",
  },
  unknown: "We couldn't complete that request. Please try again.",
};
